### ISSUE TITLE
Query HydroShare Resource Content Failure

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#18]
When running the Welcome page, at this code block
get resource content.  Returns a dictionary of filenames and their paths 
content = hs.getResourceFromHydroShare(os.environ['HS_RES_ID'])
I frequently (80% of the time) get this error. 
Downloading ..Received error BadZipFile('File is not a zip file',) when unzipping BagIt archive to /home/jovyan/work/notebooks/data.

My work around is to rerun, rerun, and rerun, and then eventually it loads.  
1. What's the problem?
2.  Is there something the user needs to do to avoid it?
3. This error message isn't helpful. The user is trying to open a ipynb and it's confusing to get a message about a zip file. 

This is my favorite part of HydroShare!! It's so awesome. Thanks for putting it together and working through these issues.

**Comment by Castronova** [comment]
My initial thought is that something is failing during file download.  Unfortunately I have not been able to replicate this error.  I'm adding a `High Priority` label since this is a bug in the core functionality.

1. is there a particular resource ID or type that causes this error?  
2. does this happen on both the NCSA and USU servers?

**Comment by Castronova** [comment]
@dtarb has also encountered this issue:

```
content = hs.getResourceFromHydroShare('25ce788b7bdb4d93af2c00f1131b8933')

Downloading ..Received error BadZipFile('File is not a zip file',) when unzipping BagIt archive to /home/jovyan/work/notebooks/data.
```

**Comment by Castronova** [comment]
@ChristinaB What resource type is giving you this error?

**Comment by leonard-psu** [comment]
Tony and Christina,
I was getting this error message on a "generic resource". If I attempted to load the resource in a web app, then retry  content = hs.getResourceFromHydroShare( XXX ) then I didn't get the error.

**Comment by leonard-psu** [comment]
I can reproduce the problem by uploading a "generic resource", i.e. ETV zip file.
Then w/o using HydroShare apps, 
I create a jupyter notebook with these lines

# import required libaries for geoprocessing
import os
import hs_utils
%matplotlib inline
hs = hs_utils.hydroshare()
replace XXX with id of uploaded file
content = hs.getResourceFromHydroShare('XXX')

I get the error message.
Then if I try to load the generic resource with a HydroShare app i.e. document viewer, then retry the above jupyter notebook script, the script works.

**Comment by Castronova** [comment]
@lorne can you share this resource with me so that i can test.

**Comment by leonard-psu** [comment]
Tony this one should replicate the problem (i.e download the zip file, and create a new resource )
https://www.hydroshare.org/resource/2bca3052389d4b509a82444031af7f4d/
the resource I was able to replicate is a 70mb zip file, if you want that one, do you a google drive location?

**Comment by Castronova** [comment]
@leonard-psu This resource works fine for me.  I wonder if its a *timeout* issue on large files.

```
import hs_utils
hs = hs_utils.hydroshare()
content = hs.getResourceFromHydroShare('2bca3052389d4b509a82444031af7f4d')
```

```
Download Completed Successfully
Found the following file(s) associated with this HydroShare resource.
HUC12_060102020105_7_12_2016_1_52_PM.zip
These files are stored in a dictionary called hs.content for your convenience. To access a file, simply issue the following command where MY_FILE is one of the files listed above:
hs.content["MY_FILE"] 
```

**Comment by Castronova** [comment]
@leonard-psu Can you try using the `hs_restclient` directly to see if you get a more informative error? 

```
from hs_restclient import HydroShare, HydroShareAuthBasic, HydroShareHTTPException
auth = HydroShareAuthBasic(username='USERNAME', password='PASSWORD')
hs = HydroShare(auth=auth)
resid = '2bca3052389d4b509a82444031af7f4d'
hs.getResource(resid, destination='.', unzip=True)
```

**Comment by leonard-psu** [comment]
* Is the timeout occurring when network and/or disk is busy? 
* I can't reproduce the problem this morning.  I notice server response was faster than previous tests.
* I was using the hs_utils library on USU notebook environment. I tested method on both NCSA and USU and had no issues this morning.

* When I try a direct method using the hs_restclient directly, I get the following error message
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\tony_test.py", line 5, in <module>
    hs.getResource(resid, destination='c:/temp', unzip=True)
  File "C:\Python\Python35\lib\site-packages\hs_restclient\__init__.py", line 499, in getResource
    self._storeBagOnFilesystem(stream, pid, destination, unzip)
  File "C:\Python\Python35\lib\site-packages\hs_restclient\__init__.py", line 532, in _storeBagOnFilesystem
    shutil.rmtree(tempdir)
  File "C:\Python\Python35\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python\Python35\lib\shutil.py", line 383, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python\Python35\lib\shutil.py", line 381, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpfjevg4pq\\6dcfd70acf404c56b3636a2507d171b2.zip'
>>>

**Comment by Castronova** [comment]
Looks like you got a permission error when you ran the script.  Next time you encounter the `Downloading ..Received error BadZipFile('File is not a zip file',) when unzipping BagIt archive to /home/jovyan/work/notebooks/data.` error, try running the code snippet above inside the notebook environment. Hopefully this will give us a more informative error.

**Comment by leonard-psu** [comment]
New generic resource test today
hs = HydroShare(auth=auth)
resid = '7855f8445b39427190a1dfcf5e2c140b'
hs.getResource(resid, destination='.', unzip=True)

error message from Jupyter notebook on USU

Received error BadZipfile('File is not a zip file',) when unzipping
BagIt archive to ..
