### ISSUE TITLE
Authorize NFIE summer school message on NCSA server

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare-jupyterhub#20]
@ddcamiu    When the user opens with NCSA, the first message they see is confusing. They don't have anything to do with the school and are not sure if they should 'authorize'.  
Suggest updating to generic message.  
Thanks!

**Comment by ddcamiu** [comment]
Should turn to @Castronova

**Comment by Castronova** [comment]
@ddcamiu Does this have to do with the NCSA OAuth settings?

**Comment by Castronova** [comment]
@ddcamiu I believe this page is managed on the NCSA server.  It can be disabled by selecting `Skip authorization` on the oauth applications page (hydroshare.org/o/applications).

![image](https://cloud.githubusercontent.com/assets/4822372/20530064/4340b934-b0a0-11e6-9b18-5e91da5d1852.png)

This is something that you need to do since you registered the server as an OAuth application within HydroShare.
